#!/usr/bin/env sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config \
  debug_output on \
  mouse_follows_focus on \
  top_padding 12 \
  left_padding 12 \
  right_padding 12 \
  bottom_padding 12 \
  layout stack

echo "yabai config loaded..."


options=(
	style=round
	width=6.0
	hidpi=on
	active_color=0xff89b4fa
	inactive_color=0xff11111b
  blur_radius=0.0
)

borders "${options[@]}" &
