#!/usr/bin/env sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# windows rules
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Raycast$" manage=off

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"

# global settings
yabai -m config \
	debug_output on \
	external_bar all:32:0 \
	mouse_follows_focus on \
	focus_follows_mouse autofocus \
	window_placement second_child \
	window_shadow off \
	active_window_opacity 0.90 \
	normal_window_opacity 0.70 \
	window_opacity off \
	split_ratio 0.50 \
	auto_balance off \
	top_padding 10 \
	left_padding 10 \
	right_padding 10 \
	bottom_padding 10 \
	window_gap 10 \
	layout bsp \
	mouse_modifier ctrl \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

echo "yabai config loaded..."

borders active_color=0xffb4befe inactive_color=0xff313244 width=3.0 &
