#!/usr/bin/env sh

# global settings
yabai -m config \
  debug_output on \
  mouse_follows_focus on \
  top_padding 12 \
  left_padding 12 \
  right_padding 12 \
  bottom_padding 12 \
  layout stack

echo "yabai config loaded..."


options=(
	style=round
	width=6.0
	hidpi=on
	active_color=0xff89b4fa
	inactive_color=0xff11111b
  blur_radius=0.0
)

borders "${options[@]}" &
